### ISSUE TITLE
RG350 version

### ISSUE THREAD

**Issue by CalebCDE** [szymor/anarch#1]
Hi! The game works in the RG350 / CGW-ZERO handheld but we haven't the anarch.gcw0.desktop.

I've make one if you're interested
[Desktop Entry]
Name=Anarch
Comment=The suckless FPS game
Exec=anarch
Terminal=false
StartupNotify=true
Icon=anarch
Categories=games;
X-OD-Manual=README.md

Thanks!

**Comment by szymor** [comment]
If you want to contribute, please fork the repository and create a proper pull request. Publishing the binaries for GCW0 would be nice as well.

**Comment by CalebCDE** [comment]
Done, thanks for the quick reply
